### ISSUE TITLE
Fix missing items, some contribution

### ISSUE THREAD

**Issue by the-j0k3r** [Obsidian-StudiosInc/Travis-CI-Dark-Purple#1]
I appreciate you taking the time to make a travis CI theme.
After reading about it at https://github.com/StylishThemes/GitHub-Dark/issues/606 I decided to try it.

I found some areas you did not style and I did some changes to formatting and some cleanup to make the style more readable to try understand what you did so I could fix it.

The changes below have removed the purple color, but I feel it should be a choice as per user like Github-Dark and not a harcoded personal preference. That said, its up to you to do wahtever you like with your work.

Here I submit below the changes I did, feel free to take fixes or not, do what you want and instead put back the purple color or whatever you like.

You have full licence to do whatever you like with the code below, and you you feel generous and use it, give credit.

```css
  body,
  aside#left,
  button,
  footer,
  .build-commit,
  .build-info,
  .build-list,
  .build-list li,
  .build-tiles li,
  .build-tools,
  .dupa,
  .main,
  .navigation-nested,
  .notice-banner--yellow,
  .option-dropdown,
  .repos-list,
  .row-branch:hover a,
  .tile.started,
  .top,
  .topbar,
  .wrapper,
  .wrapper-main,
  #travis-search {
    background-color: #222 !important;
  }

  pre {
    background: #222 !important;
    color: #eee !important;
  }

  .codedisplay.code-block.ember-view.language-json,
  .token.operator,
  code[class*="language-"],
  pre[class*="language-"] {
    background-color: #111 !important;
    text-shadow: none !important;
  }

  .job-lang {
  	background-color: #222;
  	border-bottom: 1px solid #444;
  	padding-bottom: 6px !important;
  }

  .job-lang:hover {
  	background-color: #222;
  	padding-bottom: 6px !important;
  }

  .jobs-list {
  	color: #666 !important;
  }

  .repo-navigation,
  .repo-navigation .option-display,
  .option-tofu,
  .build-header.passed.ember-view,
  .branch-row,
  .ember-view,
  .two-line.fade-out,
  .job-number {
    border-color: #555 !important;
    color: #666 !important;
  }

  .cta,
  .log-header {
    background: #333 !important;
    border-color: #444 !important;
    border-width: 1px !important;
  }

  .top .cta p::after,
  .top .cta p::before,
  .top .cta p::after {
  	filter: invert(80%) !important;
  }

  .repo-navigation .option-display:hover,
  .option-tofu:hover {
  	border-color: #3eaaaf !important;
  	color: #3eaaaf !important;
  }

  .download-log-button {
    border-color: #444 !important;
    color: #eee !important;
    background-color: #555 !important;
  }

  .download-log-button:hover {
  	border-color: #3eaaaf !important;
    background-color: #3eaaaf !important;
  }

  .job-env:hover,
  .navigation-nested a:hover {
  	background: #444 !important;
  }

  .job-lang:hover {
  	background: inherit !important;
  }

  .ember-tooltip {
    background:#000 !important;
		text-decoration: none !important;
  }

  .logo a:hover, 
  .repo-gh,
  .st5 {
		filter: invert(88%) hue-rotate(180deg) !important;
  }

  .repo-title a {
	  border-color: #222 !important;
    color: #c0c0c0 !important;
  }

  .repo-title a:hover {
	  border-color: #444 !important;
    color: #c0c0c0 !important;
  }

  .build-commit::after,
  .fade-out::after,
  .job-lang:after,
  .job-env:after,
  .owner-info::after,
  .row-message::after,
  .row-branch.booting::after,
  .row-branch.canceled::after,
  .row-branch.created::after,
  .row-branch.errored::after,
  .row-branch.failed::after,
  .row-branch.passed::after,
  .row-branch.queued::after,
  .row-branch.received::after,
  .row-branch.started::after,
  .tile-title.booting::after,
  .tile-title.canceled::after,
  .tile-title.created::after,
  .tile-title.errored::after,
  .tile-title.failed::after,
  .tile-title.passed::after,
  .tile-title.queued::after,
  .tile-title.received::after,
  .tile-title.started::after {
  	background: linear-gradient(-90deg, #222 20%, rgba(255, 255, 255, 0) 100%) !important;
  }

  .commit-description::after {
  	background: linear-gradient(360deg, #222 5%, rgba(255, 255, 255, 0) 100%) !important;
  }

  li.canceled,
  .tile.canceled {
  	background: linear-gradient(to right, #9d9d9d 0, #9d9d9d 10px, #222 10px, #222 100%) no-repeat !important;
  }

  li.errored,
  li.failed,
  .tile.errored,
  .tile.failed {
  	background: linear-gradient(to right, #db4545 0, #db4545 10px, #222 10px, #222 100%) no-repeat !important;
  }

  li.passed,
  .tile.passed {
  	background: linear-gradient(to right, #39aa56 0, #39aa56 8px, #222 8px, #222 100%) no-repeat !important;
  	border-color: #444 !important;
  }

  li.booting,
  li.created,
  li.queued,
  li.received,
  li.started,
  .tile.booting,
  .tile.created,
  .tile.queued,
  .tile.received,
  .tile.started {
  	background: linear-gradient(to right, #edde3f 0, #edde3f 8px, #222 8px, #222 100%) no-repeat !important;
  }

  .active,
  .repo-header,
  #navigation-anchor,
  nav a {
  	color: #eee !important;
  }
```
